//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEcxTrackEntities : DbContext
    {
        public DbEcxTrackEntities()
            : base("name=DbEcxTrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Acesso> TB_Acesso { get; set; }
        public virtual DbSet<TB_AlertaEventos> TB_AlertaEventos { get; set; }
        public virtual DbSet<TB_Banco> TB_Banco { get; set; }
        public virtual DbSet<TB_Cerca> TB_Cerca { get; set; }
        public virtual DbSet<TB_CercasVeiculos> TB_CercasVeiculos { get; set; }
        public virtual DbSet<TB_ChipEquipamento> TB_ChipEquipamento { get; set; }
        public virtual DbSet<TB_Cidade> TB_Cidade { get; set; }
        public virtual DbSet<TB_Cliente> TB_Cliente { get; set; }
        public virtual DbSet<TB_ComandosAlertas> TB_ComandosAlertas { get; set; }
        public virtual DbSet<TB_Complemento> TB_Complemento { get; set; }
        public virtual DbSet<TB_Contrato> TB_Contrato { get; set; }
        public virtual DbSet<TB_EmailNotificacao> TB_EmailNotificacao { get; set; }
        public virtual DbSet<TB_EnderecoPrefCampanha> TB_EnderecoPrefCampanha { get; set; }
        public virtual DbSet<TB_EnderecosEventos> TB_EnderecosEventos { get; set; }
        public virtual DbSet<TB_EntradasEquipamento> TB_EntradasEquipamento { get; set; }
        public virtual DbSet<TB_Equipamento> TB_Equipamento { get; set; }
        public virtual DbSet<TB_Estado> TB_Estado { get; set; }
        public virtual DbSet<TB_EventoVerificacao> TB_EventoVerificacao { get; set; }
        public virtual DbSet<TB_Financeiro> TB_Financeiro { get; set; }
        public virtual DbSet<TB_FusoHorario> TB_FusoHorario { get; set; }
        public virtual DbSet<TB_GoogleCache> TB_GoogleCache { get; set; }
        public virtual DbSet<TB_HorarioOcorrencia> TB_HorarioOcorrencia { get; set; }
        public virtual DbSet<TB_ImagemPontos> TB_ImagemPontos { get; set; }
        public virtual DbSet<TB_IntervaloJornada> TB_IntervaloJornada { get; set; }
        public virtual DbSet<TB_Jornada> TB_Jornada { get; set; }
        public virtual DbSet<TB_LogSistema> TB_LogSistema { get; set; }
        public virtual DbSet<TB_Manutencao> TB_Manutencao { get; set; }
        public virtual DbSet<TB_Marca> TB_Marca { get; set; }
        public virtual DbSet<TB_Mensagens> TB_Mensagens { get; set; }
        public virtual DbSet<TB_ModeloEquipamento> TB_ModeloEquipamento { get; set; }
        public virtual DbSet<TB_ModeloVeiculo> TB_ModeloVeiculo { get; set; }
        public virtual DbSet<TB_Motorista> TB_Motorista { get; set; }
        public virtual DbSet<TB_NotificaoVeiculo> TB_NotificaoVeiculo { get; set; }
        public virtual DbSet<TB_Ocorrencia> TB_Ocorrencia { get; set; }
        public virtual DbSet<TB_Operadora> TB_Operadora { get; set; }
        public virtual DbSet<TB_OrdemServico> TB_OrdemServico { get; set; }
        public virtual DbSet<TB_Pagina> TB_Pagina { get; set; }
        public virtual DbSet<TB_Perfil> TB_Perfil { get; set; }
        public virtual DbSet<TB_PerfilRestricao> TB_PerfilRestricao { get; set; }
        public virtual DbSet<TB_Permissao> TB_Permissao { get; set; }
        public virtual DbSet<TB_PessoaProcedimento> TB_PessoaProcedimento { get; set; }
        public virtual DbSet<TB_Pontos> TB_Pontos { get; set; }
        public virtual DbSet<TB_PontosCerca> TB_PontosCerca { get; set; }
        public virtual DbSet<TB_PontosRota> TB_PontosRota { get; set; }
        public virtual DbSet<TB_ReferenciaBancaria> TB_ReferenciaBancaria { get; set; }
        public virtual DbSet<TB_RegraJornada> TB_RegraJornada { get; set; }
        public virtual DbSet<TB_Representante> TB_Representante { get; set; }
        public virtual DbSet<TB_RevisaoFuncionamento> TB_RevisaoFuncionamento { get; set; }
        public virtual DbSet<TB_Rota> TB_Rota { get; set; }
        public virtual DbSet<TB_RotasVeiculos> TB_RotasVeiculos { get; set; }
        public virtual DbSet<TB_SaidasEquipamento> TB_SaidasEquipamento { get; set; }
        public virtual DbSet<TB_Servico> TB_Servico { get; set; }
        public virtual DbSet<TB_SmsNotificacao> TB_SmsNotificacao { get; set; }
        public virtual DbSet<TB_TipoOcorrencia> TB_TipoOcorrencia { get; set; }
        public virtual DbSet<TB_TipoPerfil> TB_TipoPerfil { get; set; }
        public virtual DbSet<TB_TipoVeiculo> TB_TipoVeiculo { get; set; }
        public virtual DbSet<TB_TipoVerificacao> TB_TipoVerificacao { get; set; }
        public virtual DbSet<TB_TratamentoAlerta> TB_TratamentoAlerta { get; set; }
        public virtual DbSet<TB_Usuario> TB_Usuario { get; set; }
        public virtual DbSet<TB_Veiculo> TB_Veiculo { get; set; }
        public virtual DbSet<TB_VeiculosClientes> TB_VeiculosClientes { get; set; }
        public virtual DbSet<TB_VeiculosEquipamentos> TB_VeiculosEquipamentos { get; set; }
        public virtual DbSet<TB_Verificacao> TB_Verificacao { get; set; }
        public virtual DbSet<TBS_Evento> TBS_Evento { get; set; }
        public virtual DbSet<TBS_Requisicao> TBS_Requisicao { get; set; }
        public virtual DbSet<TBS_RequisicaoApn> TBS_RequisicaoApn { get; set; }
        public virtual DbSet<TBS_RequisicaoHodometro> TBS_RequisicaoHodometro { get; set; }
        public virtual DbSet<TBS_RequisicaoServer> TBS_RequisicaoServer { get; set; }
        public virtual DbSet<TBS_RequisicaoSleepConfig> TBS_RequisicaoSleepConfig { get; set; }
        public virtual DbSet<TBS_RequisicaoTempoTransmissao> TBS_RequisicaoTempoTransmissao { get; set; }
        public virtual DbSet<TBS_StatusRequisicao> TBS_StatusRequisicao { get; set; }
        public virtual DbSet<TBS_TipoEvento> TBS_TipoEvento { get; set; }
        public virtual DbSet<TBS_TipoRequisicao> TBS_TipoRequisicao { get; set; }
        public virtual DbSet<TB_JornadaMaxima> TB_JornadaMaxima { get; set; }
        public virtual DbSet<TBS_ImeiSimCard> TBS_ImeiSimCard { get; set; }
    
        public virtual int Proc_DeslocParada(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<int> codVeiculo, Nullable<bool> intervaloHoras)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var codVeiculoParameter = codVeiculo.HasValue ?
                new ObjectParameter("CodVeiculo", codVeiculo) :
                new ObjectParameter("CodVeiculo", typeof(int));
    
            var intervaloHorasParameter = intervaloHoras.HasValue ?
                new ObjectParameter("IntervaloHoras", intervaloHoras) :
                new ObjectParameter("IntervaloHoras", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_DeslocParada", dataInicialParameter, dataFinalParameter, codVeiculoParameter, intervaloHorasParameter);
        }
    
        public virtual int Proc_Pontos(Nullable<System.DateTime> dataIni, Nullable<double> raio, Nullable<System.DateTime> dataFim, Nullable<int> codVeiculo, string longitude, string latitude)
        {
            var dataIniParameter = dataIni.HasValue ?
                new ObjectParameter("DataIni", dataIni) :
                new ObjectParameter("DataIni", typeof(System.DateTime));
    
            var raioParameter = raio.HasValue ?
                new ObjectParameter("Raio", raio) :
                new ObjectParameter("Raio", typeof(double));
    
            var dataFimParameter = dataFim.HasValue ?
                new ObjectParameter("DataFim", dataFim) :
                new ObjectParameter("DataFim", typeof(System.DateTime));
    
            var codVeiculoParameter = codVeiculo.HasValue ?
                new ObjectParameter("CodVeiculo", codVeiculo) :
                new ObjectParameter("CodVeiculo", typeof(int));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Pontos", dataIniParameter, raioParameter, dataFimParameter, codVeiculoParameter, longitudeParameter, latitudeParameter);
        }
    
        public virtual int Proc_Rastrear_CloseRequisition(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Rastrear_CloseRequisition", codRequisicaoParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisition_Result> Proc_Rastrear_GetRequisition(string numeroSerie)
        {
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisition_Result>("Proc_Rastrear_GetRequisition", numeroSerieParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisitionApn_Result> Proc_Rastrear_GetRequisitionApn(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisitionApn_Result>("Proc_Rastrear_GetRequisitionApn", codRequisicaoParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisitionOdometer_Result> Proc_Rastrear_GetRequisitionOdometer(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisitionOdometer_Result>("Proc_Rastrear_GetRequisitionOdometer", codRequisicaoParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisitionServer_Result> Proc_Rastrear_GetRequisitionServer(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisitionServer_Result>("Proc_Rastrear_GetRequisitionServer", codRequisicaoParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisitionSleepTime_Result> Proc_Rastrear_GetRequisitionSleepTime(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisitionSleepTime_Result>("Proc_Rastrear_GetRequisitionSleepTime", codRequisicaoParameter);
        }
    
        public virtual ObjectResult<Proc_Rastrear_GetRequisitionTransmissionTime_Result> Proc_Rastrear_GetRequisitionTransmissionTime(Nullable<int> codRequisicao)
        {
            var codRequisicaoParameter = codRequisicao.HasValue ?
                new ObjectParameter("CodRequisicao", codRequisicao) :
                new ObjectParameter("CodRequisicao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Rastrear_GetRequisitionTransmissionTime_Result>("Proc_Rastrear_GetRequisitionTransmissionTime", codRequisicaoParameter);
        }
    
        public virtual int Proc_Rastrear_SaveImei(string numeroSerie, Nullable<int> codModeloBin, Nullable<System.DateTime> dataEnvio, string imei, string simCard)
        {
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            var codModeloBinParameter = codModeloBin.HasValue ?
                new ObjectParameter("CodModeloBin", codModeloBin) :
                new ObjectParameter("CodModeloBin", typeof(int));
    
            var dataEnvioParameter = dataEnvio.HasValue ?
                new ObjectParameter("DataEnvio", dataEnvio) :
                new ObjectParameter("DataEnvio", typeof(System.DateTime));
    
            var imeiParameter = imei != null ?
                new ObjectParameter("Imei", imei) :
                new ObjectParameter("Imei", typeof(string));
    
            var simCardParameter = simCard != null ?
                new ObjectParameter("SimCard", simCard) :
                new ObjectParameter("SimCard", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Rastrear_SaveImei", numeroSerieParameter, codModeloBinParameter, dataEnvioParameter, imeiParameter, simCardParameter);
        }
    
        public virtual int Proc_Rastrear_SaveTracking(string numeroSerie, Nullable<int> codModeloBin, Nullable<System.DateTime> dataEvento, Nullable<System.DateTime> dataComunicacao, Nullable<decimal> latitude, Nullable<decimal> longitude, Nullable<short> direcao, Nullable<short> velocidade, Nullable<short> sinalGPS, Nullable<short> codTipoEvento, Nullable<short> bateria, Nullable<short> temperatura, Nullable<int> hodometro, Nullable<int> statusEntradas, Nullable<int> statusSaida, Nullable<bool> statusIgnicao, Nullable<bool> statusBotaoPanico, Nullable<bool> statusEntradaAuxiliar, Nullable<bool> statusBotaoAntiFurto, Nullable<bool> statusSecaoAntenaGPS, Nullable<bool> statusVoltagemBateria, Nullable<bool> statusEntradaAuxiliar2, Nullable<bool> statusEntradaAuxiliar4, Nullable<bool> statusBateriaBkpBaixa, Nullable<bool> statusFalhaBateriaBkp, Nullable<bool> statusFimVidaUtilBateriaBkp, Nullable<bool> statusBloqueio, Nullable<bool> statusSirene, Nullable<bool> statusSaidaAuxiliar, Nullable<bool> statusSaidaAuxiliar2, Nullable<bool> statusSaidaAuxiliar3, Nullable<bool> statusSaidaAuxiliar4)
        {
            var numeroSerieParameter = numeroSerie != null ?
                new ObjectParameter("NumeroSerie", numeroSerie) :
                new ObjectParameter("NumeroSerie", typeof(string));
    
            var codModeloBinParameter = codModeloBin.HasValue ?
                new ObjectParameter("CodModeloBin", codModeloBin) :
                new ObjectParameter("CodModeloBin", typeof(int));
    
            var dataEventoParameter = dataEvento.HasValue ?
                new ObjectParameter("DataEvento", dataEvento) :
                new ObjectParameter("DataEvento", typeof(System.DateTime));
    
            var dataComunicacaoParameter = dataComunicacao.HasValue ?
                new ObjectParameter("DataComunicacao", dataComunicacao) :
                new ObjectParameter("DataComunicacao", typeof(System.DateTime));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(decimal));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(decimal));
    
            var direcaoParameter = direcao.HasValue ?
                new ObjectParameter("Direcao", direcao) :
                new ObjectParameter("Direcao", typeof(short));
    
            var velocidadeParameter = velocidade.HasValue ?
                new ObjectParameter("Velocidade", velocidade) :
                new ObjectParameter("Velocidade", typeof(short));
    
            var sinalGPSParameter = sinalGPS.HasValue ?
                new ObjectParameter("SinalGPS", sinalGPS) :
                new ObjectParameter("SinalGPS", typeof(short));
    
            var codTipoEventoParameter = codTipoEvento.HasValue ?
                new ObjectParameter("CodTipoEvento", codTipoEvento) :
                new ObjectParameter("CodTipoEvento", typeof(short));
    
            var bateriaParameter = bateria.HasValue ?
                new ObjectParameter("Bateria", bateria) :
                new ObjectParameter("Bateria", typeof(short));
    
            var temperaturaParameter = temperatura.HasValue ?
                new ObjectParameter("Temperatura", temperatura) :
                new ObjectParameter("Temperatura", typeof(short));
    
            var hodometroParameter = hodometro.HasValue ?
                new ObjectParameter("Hodometro", hodometro) :
                new ObjectParameter("Hodometro", typeof(int));
    
            var statusEntradasParameter = statusEntradas.HasValue ?
                new ObjectParameter("StatusEntradas", statusEntradas) :
                new ObjectParameter("StatusEntradas", typeof(int));
    
            var statusSaidaParameter = statusSaida.HasValue ?
                new ObjectParameter("StatusSaida", statusSaida) :
                new ObjectParameter("StatusSaida", typeof(int));
    
            var statusIgnicaoParameter = statusIgnicao.HasValue ?
                new ObjectParameter("StatusIgnicao", statusIgnicao) :
                new ObjectParameter("StatusIgnicao", typeof(bool));
    
            var statusBotaoPanicoParameter = statusBotaoPanico.HasValue ?
                new ObjectParameter("StatusBotaoPanico", statusBotaoPanico) :
                new ObjectParameter("StatusBotaoPanico", typeof(bool));
    
            var statusEntradaAuxiliarParameter = statusEntradaAuxiliar.HasValue ?
                new ObjectParameter("StatusEntradaAuxiliar", statusEntradaAuxiliar) :
                new ObjectParameter("StatusEntradaAuxiliar", typeof(bool));
    
            var statusBotaoAntiFurtoParameter = statusBotaoAntiFurto.HasValue ?
                new ObjectParameter("StatusBotaoAntiFurto", statusBotaoAntiFurto) :
                new ObjectParameter("StatusBotaoAntiFurto", typeof(bool));
    
            var statusSecaoAntenaGPSParameter = statusSecaoAntenaGPS.HasValue ?
                new ObjectParameter("StatusSecaoAntenaGPS", statusSecaoAntenaGPS) :
                new ObjectParameter("StatusSecaoAntenaGPS", typeof(bool));
    
            var statusVoltagemBateriaParameter = statusVoltagemBateria.HasValue ?
                new ObjectParameter("StatusVoltagemBateria", statusVoltagemBateria) :
                new ObjectParameter("StatusVoltagemBateria", typeof(bool));
    
            var statusEntradaAuxiliar2Parameter = statusEntradaAuxiliar2.HasValue ?
                new ObjectParameter("StatusEntradaAuxiliar2", statusEntradaAuxiliar2) :
                new ObjectParameter("StatusEntradaAuxiliar2", typeof(bool));
    
            var statusEntradaAuxiliar4Parameter = statusEntradaAuxiliar4.HasValue ?
                new ObjectParameter("StatusEntradaAuxiliar4", statusEntradaAuxiliar4) :
                new ObjectParameter("StatusEntradaAuxiliar4", typeof(bool));
    
            var statusBateriaBkpBaixaParameter = statusBateriaBkpBaixa.HasValue ?
                new ObjectParameter("StatusBateriaBkpBaixa", statusBateriaBkpBaixa) :
                new ObjectParameter("StatusBateriaBkpBaixa", typeof(bool));
    
            var statusFalhaBateriaBkpParameter = statusFalhaBateriaBkp.HasValue ?
                new ObjectParameter("StatusFalhaBateriaBkp", statusFalhaBateriaBkp) :
                new ObjectParameter("StatusFalhaBateriaBkp", typeof(bool));
    
            var statusFimVidaUtilBateriaBkpParameter = statusFimVidaUtilBateriaBkp.HasValue ?
                new ObjectParameter("StatusFimVidaUtilBateriaBkp", statusFimVidaUtilBateriaBkp) :
                new ObjectParameter("StatusFimVidaUtilBateriaBkp", typeof(bool));
    
            var statusBloqueioParameter = statusBloqueio.HasValue ?
                new ObjectParameter("StatusBloqueio", statusBloqueio) :
                new ObjectParameter("StatusBloqueio", typeof(bool));
    
            var statusSireneParameter = statusSirene.HasValue ?
                new ObjectParameter("StatusSirene", statusSirene) :
                new ObjectParameter("StatusSirene", typeof(bool));
    
            var statusSaidaAuxiliarParameter = statusSaidaAuxiliar.HasValue ?
                new ObjectParameter("StatusSaidaAuxiliar", statusSaidaAuxiliar) :
                new ObjectParameter("StatusSaidaAuxiliar", typeof(bool));
    
            var statusSaidaAuxiliar2Parameter = statusSaidaAuxiliar2.HasValue ?
                new ObjectParameter("StatusSaidaAuxiliar2", statusSaidaAuxiliar2) :
                new ObjectParameter("StatusSaidaAuxiliar2", typeof(bool));
    
            var statusSaidaAuxiliar3Parameter = statusSaidaAuxiliar3.HasValue ?
                new ObjectParameter("StatusSaidaAuxiliar3", statusSaidaAuxiliar3) :
                new ObjectParameter("StatusSaidaAuxiliar3", typeof(bool));
    
            var statusSaidaAuxiliar4Parameter = statusSaidaAuxiliar4.HasValue ?
                new ObjectParameter("StatusSaidaAuxiliar4", statusSaidaAuxiliar4) :
                new ObjectParameter("StatusSaidaAuxiliar4", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Rastrear_SaveTracking", numeroSerieParameter, codModeloBinParameter, dataEventoParameter, dataComunicacaoParameter, latitudeParameter, longitudeParameter, direcaoParameter, velocidadeParameter, sinalGPSParameter, codTipoEventoParameter, bateriaParameter, temperaturaParameter, hodometroParameter, statusEntradasParameter, statusSaidaParameter, statusIgnicaoParameter, statusBotaoPanicoParameter, statusEntradaAuxiliarParameter, statusBotaoAntiFurtoParameter, statusSecaoAntenaGPSParameter, statusVoltagemBateriaParameter, statusEntradaAuxiliar2Parameter, statusEntradaAuxiliar4Parameter, statusBateriaBkpBaixaParameter, statusFalhaBateriaBkpParameter, statusFimVidaUtilBateriaBkpParameter, statusBloqueioParameter, statusSireneParameter, statusSaidaAuxiliarParameter, statusSaidaAuxiliar2Parameter, statusSaidaAuxiliar3Parameter, statusSaidaAuxiliar4Parameter);
        }
    
        public virtual ObjectResult<Proc_RelatorioVelocidade_Result> Proc_RelatorioVelocidade(Nullable<System.DateTime> dataIni, Nullable<int> velocidade, Nullable<System.DateTime> dataFim, Nullable<int> codVeiculoMotorista, string tipoRelatorio)
        {
            var dataIniParameter = dataIni.HasValue ?
                new ObjectParameter("DataIni", dataIni) :
                new ObjectParameter("DataIni", typeof(System.DateTime));
    
            var velocidadeParameter = velocidade.HasValue ?
                new ObjectParameter("Velocidade", velocidade) :
                new ObjectParameter("Velocidade", typeof(int));
    
            var dataFimParameter = dataFim.HasValue ?
                new ObjectParameter("DataFim", dataFim) :
                new ObjectParameter("DataFim", typeof(System.DateTime));
    
            var codVeiculoMotoristaParameter = codVeiculoMotorista.HasValue ?
                new ObjectParameter("CodVeiculoMotorista", codVeiculoMotorista) :
                new ObjectParameter("CodVeiculoMotorista", typeof(int));
    
            var tipoRelatorioParameter = tipoRelatorio != null ?
                new ObjectParameter("TipoRelatorio", tipoRelatorio) :
                new ObjectParameter("TipoRelatorio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_RelatorioVelocidade_Result>("Proc_RelatorioVelocidade", dataIniParameter, velocidadeParameter, dataFimParameter, codVeiculoMotoristaParameter, tipoRelatorioParameter);
        }
    
        public virtual int Proc_RelEntrada(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<int> codVeiculo, Nullable<bool> intervaloHoras)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var codVeiculoParameter = codVeiculo.HasValue ?
                new ObjectParameter("CodVeiculo", codVeiculo) :
                new ObjectParameter("CodVeiculo", typeof(int));
    
            var intervaloHorasParameter = intervaloHoras.HasValue ?
                new ObjectParameter("IntervaloHoras", intervaloHoras) :
                new ObjectParameter("IntervaloHoras", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_RelEntrada", dataInicialParameter, dataFinalParameter, codVeiculoParameter, intervaloHorasParameter);
        }
    
        public virtual int Proc_RelEntrada_old(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<int> codVeiculo, Nullable<bool> intervaloHoras)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var codVeiculoParameter = codVeiculo.HasValue ?
                new ObjectParameter("CodVeiculo", codVeiculo) :
                new ObjectParameter("CodVeiculo", typeof(int));
    
            var intervaloHorasParameter = intervaloHoras.HasValue ?
                new ObjectParameter("IntervaloHoras", intervaloHoras) :
                new ObjectParameter("IntervaloHoras", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_RelEntrada_old", dataInicialParameter, dataFinalParameter, codVeiculoParameter, intervaloHorasParameter);
        }
    
        public virtual int Proc_VerificarRotas(Nullable<System.DateTime> dataVinculacao, Nullable<double> raio, Nullable<decimal> longitude, Nullable<decimal> latitude, Nullable<int> codVeiculo)
        {
            var dataVinculacaoParameter = dataVinculacao.HasValue ?
                new ObjectParameter("DataVinculacao", dataVinculacao) :
                new ObjectParameter("DataVinculacao", typeof(System.DateTime));
    
            var raioParameter = raio.HasValue ?
                new ObjectParameter("Raio", raio) :
                new ObjectParameter("Raio", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(decimal));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(decimal));
    
            var codVeiculoParameter = codVeiculo.HasValue ?
                new ObjectParameter("CodVeiculo", codVeiculo) :
                new ObjectParameter("CodVeiculo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_VerificarRotas", dataVinculacaoParameter, raioParameter, longitudeParameter, latitudeParameter, codVeiculoParameter);
        }
    
        public virtual int Utility_EstimateClusteredIndexSize(Nullable<double> num_Rows, Nullable<bool> clusteredIndexIsUnique, Nullable<double> fill_Factor)
        {
            var num_RowsParameter = num_Rows.HasValue ?
                new ObjectParameter("Num_Rows", num_Rows) :
                new ObjectParameter("Num_Rows", typeof(double));
    
            var clusteredIndexIsUniqueParameter = clusteredIndexIsUnique.HasValue ?
                new ObjectParameter("ClusteredIndexIsUnique", clusteredIndexIsUnique) :
                new ObjectParameter("ClusteredIndexIsUnique", typeof(bool));
    
            var fill_FactorParameter = fill_Factor.HasValue ?
                new ObjectParameter("Fill_Factor", fill_Factor) :
                new ObjectParameter("Fill_Factor", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Utility_EstimateClusteredIndexSize", num_RowsParameter, clusteredIndexIsUniqueParameter, fill_FactorParameter);
        }
    }
}
