//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AlertaEventos
    {
        public TB_AlertaEventos()
        {
            this.TB_TratamentoAlerta = new HashSet<TB_TratamentoAlerta>();
        }
    
        public int CodAlerta { get; set; }
        public Nullable<long> CodEvento { get; set; }
        public Nullable<int> CodCerca { get; set; }
        public Nullable<int> CodVeiculo { get; set; }
        public Nullable<int> CodRota { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public int TipoEvento { get; set; }
        public Nullable<int> ChaveAlerta { get; set; }
        public string Personalizado { get; set; }
        public Nullable<int> CodEventoVerificacao { get; set; }
    
        public virtual TB_EventoVerificacao TB_EventoVerificacao { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
        public virtual ICollection<TB_TratamentoAlerta> TB_TratamentoAlerta { get; set; }
    }
}
