//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Banco
    {
        public TB_Banco()
        {
            this.TB_ReferenciaBancaria = new HashSet<TB_ReferenciaBancaria>();
        }
    
        public int CodBanco { get; set; }
        public string Nome { get; set; }
        public string CodigoPadrao { get; set; }
    
        public virtual ICollection<TB_ReferenciaBancaria> TB_ReferenciaBancaria { get; set; }
    }
}
