//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ComandosAlertas
    {
        public int CodComandosAlertas { get; set; }
        public Nullable<int> CodChaveAlerta { get; set; }
        public string DescricaoComando { get; set; }
        public Nullable<System.DateTime> DataEnvio { get; set; }
    }
}
