//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cliente
    {
        public TB_Cliente()
        {
            this.TB_Cerca = new HashSet<TB_Cerca>();
            this.TB_VeiculosClientes = new HashSet<TB_VeiculosClientes>();
            this.TB_Complemento = new HashSet<TB_Complemento>();
            this.TB_Contrato = new HashSet<TB_Contrato>();
            this.TB_EnderecoPrefCampanha = new HashSet<TB_EnderecoPrefCampanha>();
            this.TB_Motorista = new HashSet<TB_Motorista>();
            this.TB_Ocorrencia = new HashSet<TB_Ocorrencia>();
            this.TB_OrdemServico = new HashSet<TB_OrdemServico>();
            this.TB_Pontos = new HashSet<TB_Pontos>();
            this.TB_ReferenciaBancaria = new HashSet<TB_ReferenciaBancaria>();
            this.TB_RegraJornada = new HashSet<TB_RegraJornada>();
            this.TB_Representante = new HashSet<TB_Representante>();
            this.TB_Rota = new HashSet<TB_Rota>();
            this.TB_Usuario = new HashSet<TB_Usuario>();
        }
    
        public int CodCliente { get; set; }
        public string NomeCliente { get; set; }
        public string RazaoSocial { get; set; }
        public string Tipo { get; set; }
        public string CNPJ_CPF { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public int CodCidade { get; set; }
        public string CEP { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Observacoes { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int CodUsuario { get; set; }
        public Nullable<int> CodUsuarioVendas1 { get; set; }
        public Nullable<int> CodUsuarioVendas2 { get; set; }
        public string EnderecoCobranca { get; set; }
        public string NumeroCobranca { get; set; }
        public string BairroCobranca { get; set; }
        public string ComplementoCobranca { get; set; }
        public string CEPCobranca { get; set; }
        public Nullable<int> CodCidadeCobranca { get; set; }
        public string TelefoneCobranca { get; set; }
        public Nullable<System.DateTime> DataModificacao { get; set; }
        public string InscricaoMunicipal { get; set; }
        public string InscricaoEstadual { get; set; }
        public string Ativo { get; set; }
        public string GerenciadorRiscos { get; set; }
    
        public virtual ICollection<TB_Cerca> TB_Cerca { get; set; }
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Cidade TB_Cidade1 { get; set; }
        public virtual TB_Cidade TB_Cidade2 { get; set; }
        public virtual ICollection<TB_VeiculosClientes> TB_VeiculosClientes { get; set; }
        public virtual TB_Cliente TB_Cliente1 { get; set; }
        public virtual TB_Cliente TB_Cliente2 { get; set; }
        public virtual ICollection<TB_Complemento> TB_Complemento { get; set; }
        public virtual ICollection<TB_Contrato> TB_Contrato { get; set; }
        public virtual ICollection<TB_EnderecoPrefCampanha> TB_EnderecoPrefCampanha { get; set; }
        public virtual ICollection<TB_Motorista> TB_Motorista { get; set; }
        public virtual ICollection<TB_Ocorrencia> TB_Ocorrencia { get; set; }
        public virtual ICollection<TB_OrdemServico> TB_OrdemServico { get; set; }
        public virtual ICollection<TB_Pontos> TB_Pontos { get; set; }
        public virtual ICollection<TB_ReferenciaBancaria> TB_ReferenciaBancaria { get; set; }
        public virtual ICollection<TB_RegraJornada> TB_RegraJornada { get; set; }
        public virtual ICollection<TB_Representante> TB_Representante { get; set; }
        public virtual ICollection<TB_Rota> TB_Rota { get; set; }
        public virtual ICollection<TB_Usuario> TB_Usuario { get; set; }
    }
}
