//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ChipEquipamento
    {
        public int CodChipEquipamento { get; set; }
        public int CodEquipamento { get; set; }
        public string NumeroChip { get; set; }
        public string Ativo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Telefone { get; set; }
    
        public virtual TB_Equipamento TB_Equipamento { get; set; }
    }
}
