//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CercasVeiculos
    {
        public int CodVinculacao { get; set; }
        public int CodCerca { get; set; }
        public int CodVeiculo { get; set; }
        public string AlertaSonoro { get; set; }
        public string AlertarQuando { get; set; }
        public string GerarAlerta { get; set; }
        public string Status { get; set; }
    
        public virtual TB_Cerca TB_Cerca { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
