//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Contrato
    {
        public int CodContrato { get; set; }
        public int CodCliente { get; set; }
        public Nullable<double> MensalidadePorVeiculo { get; set; }
        public Nullable<decimal> ValorContratoVeiculo { get; set; }
        public Nullable<decimal> TaxaInstalacao { get; set; }
        public Nullable<decimal> ExcedentePorMegabyte { get; set; }
        public Nullable<decimal> TaxaRenovacaoContratual { get; set; }
        public Nullable<decimal> TaxaVisitaImprodutiva { get; set; }
        public Nullable<decimal> TaxaRemocaoReinstalacao { get; set; }
        public Nullable<decimal> TaxaInformacaoLocalizacaoVeiculo { get; set; }
        public Nullable<decimal> TaxaFalsoPanico { get; set; }
        public string ContemplacaoInstalacao { get; set; }
        public Nullable<int> PrazoDeValidade { get; set; }
        public Nullable<int> DataPagamento { get; set; }
        public Nullable<int> DataCorte { get; set; }
        public string Status { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
