//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cerca
    {
        public TB_Cerca()
        {
            this.TB_CercasVeiculos = new HashSet<TB_CercasVeiculos>();
            this.TB_PontosCerca = new HashSet<TB_PontosCerca>();
        }
    
        public int CodCerca { get; set; }
        public string NomeCerca { get; set; }
        public int CodCliente { get; set; }
        public Nullable<decimal> Raio { get; set; }
        public string TipoCerca { get; set; }
        public string Status { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual ICollection<TB_CercasVeiculos> TB_CercasVeiculos { get; set; }
        public virtual ICollection<TB_PontosCerca> TB_PontosCerca { get; set; }
    }
}
