//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EnderecoPrefCampanha
    {
        public int CodCliente { get; set; }
        public string RazaoSocial { get; set; }
        public string ContaContabil { get; set; }
        public string CEP { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public Nullable<int> CodCidade { get; set; }
        public string EmailCampanha { get; set; }
        public string EmailNotificacao { get; set; }
        public string Contato { get; set; }
        public string Telefone { get; set; }
        public int CodClienteEnd { get; set; }
    
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
