//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Equipamento
    {
        public TB_Equipamento()
        {
            this.TB_ChipEquipamento = new HashSet<TB_ChipEquipamento>();
            this.TBS_Evento = new HashSet<TBS_Evento>();
            this.TB_VeiculosEquipamentos = new HashSet<TB_VeiculosEquipamentos>();
            this.TBS_ImeiSimCard = new HashSet<TBS_ImeiSimCard>();
            this.TBS_Requisicao = new HashSet<TBS_Requisicao>();
        }
    
        public int CodEquipamento { get; set; }
        public string NumeroEquipamento { get; set; }
        public string NumeroSerie { get; set; }
        public string Apn { get; set; }
        public string NumeroChip { get; set; }
        public string NumeroTelefone { get; set; }
        public int CodModelo { get; set; }
        public int CodOperadora { get; set; }
        public string Ativo { get; set; }
        public string NumeroSerie2 { get; set; }
    
        public virtual ICollection<TB_ChipEquipamento> TB_ChipEquipamento { get; set; }
        public virtual ICollection<TBS_Evento> TBS_Evento { get; set; }
        public virtual TB_ModeloEquipamento TB_ModeloEquipamento { get; set; }
        public virtual TB_Operadora TB_Operadora { get; set; }
        public virtual ICollection<TB_VeiculosEquipamentos> TB_VeiculosEquipamentos { get; set; }
        public virtual ICollection<TBS_ImeiSimCard> TBS_ImeiSimCard { get; set; }
        public virtual ICollection<TBS_Requisicao> TBS_Requisicao { get; set; }
    }
}
