//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmailNotificacao
    {
        public int CodEmailNotificacao { get; set; }
        public int CodNotificacaoVeiculo { get; set; }
        public string Email { get; set; }
    
        public virtual TB_NotificaoVeiculo TB_NotificaoVeiculo { get; set; }
    }
}
