//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EnderecosEventos
    {
        public int CodEnderecoEvento { get; set; }
        public long IdEvento { get; set; }
        public int IdGoogleCache { get; set; }
    
        public virtual TB_GoogleCache TB_GoogleCache { get; set; }
        public virtual TBS_Evento TBS_Evento { get; set; }
    }
}
