//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EventoVerificacao
    {
        public TB_EventoVerificacao()
        {
            this.TB_AlertaEventos = new HashSet<TB_AlertaEventos>();
            this.TB_Veiculo = new HashSet<TB_Veiculo>();
        }
    
        public int CodEventoVerificacao { get; set; }
        public Nullable<int> CodVerificacao1 { get; set; }
        public Nullable<int> CodVerificacao2 { get; set; }
        public Nullable<int> CodVerificacao3 { get; set; }
        public int CodHorarioOcorrencia { get; set; }
        public bool AlertaSonoro { get; set; }
        public string NomeEvento { get; set; }
        public string Ativo { get; set; }
        public Nullable<int> CodComando { get; set; }
    
        public virtual ICollection<TB_AlertaEventos> TB_AlertaEventos { get; set; }
        public virtual TB_HorarioOcorrencia TB_HorarioOcorrencia { get; set; }
        public virtual TB_Verificacao TB_Verificacao { get; set; }
        public virtual TB_Verificacao TB_Verificacao1 { get; set; }
        public virtual TB_Verificacao TB_Verificacao2 { get; set; }
        public virtual ICollection<TB_Veiculo> TB_Veiculo { get; set; }
    }
}
