//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Financeiro
    {
        public int CodCliente { get; set; }
        public Nullable<bool> RetencaoISS { get; set; }
        public Nullable<System.DateTime> DataInicioRetencao { get; set; }
        public Nullable<int> QtdeEquipamento { get; set; }
        public Nullable<decimal> ValorAluguel { get; set; }
        public Nullable<int> DiaFaturamento { get; set; }
        public Nullable<int> DiaVencimento { get; set; }
        public Nullable<int> PrazoProtesto { get; set; }
        public Nullable<System.DateTime> DataUltimoFaturamento { get; set; }
        public Nullable<decimal> JurosMora { get; set; }
        public Nullable<decimal> Multa { get; set; }
    }
}
