//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GoogleCache
    {
        public TB_GoogleCache()
        {
            this.TB_EnderecosEventos = new HashSet<TB_EnderecosEventos>();
        }
    
        public int id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Posicao { get; set; }
        public string Endereco { get; set; }
        public System.DateTime DataInsert { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
    
        public virtual ICollection<TB_EnderecosEventos> TB_EnderecosEventos { get; set; }
    }
}
