//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HorarioOcorrencia
    {
        public TB_HorarioOcorrencia()
        {
            this.TB_EventoVerificacao = new HashSet<TB_EventoVerificacao>();
        }
    
        public int CodHorarioOcorrencia { get; set; }
        public Nullable<bool> Domingo { get; set; }
        public Nullable<bool> Segunda { get; set; }
        public Nullable<bool> Terca { get; set; }
        public Nullable<bool> Quarta { get; set; }
        public Nullable<bool> Quinta { get; set; }
        public Nullable<bool> Sexta { get; set; }
        public Nullable<bool> Sabado { get; set; }
        public Nullable<bool> Diariamente { get; set; }
        public Nullable<System.TimeSpan> HorarioInicial { get; set; }
        public Nullable<System.TimeSpan> HorarioFinal { get; set; }
        public Nullable<bool> TempoCorrido { get; set; }
    
        public virtual ICollection<TB_EventoVerificacao> TB_EventoVerificacao { get; set; }
    }
}
