//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ImagemPontos
    {
        public TB_ImagemPontos()
        {
            this.TB_Pontos = new HashSet<TB_Pontos>();
        }
    
        public int CodIcone { get; set; }
        public string NomeImagem { get; set; }
    
        public virtual ICollection<TB_Pontos> TB_Pontos { get; set; }
    }
}
