//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IntervaloJornada
    {
        public int CodIntervaloJornada { get; set; }
        public bool IntraJornada { get; set; }
        public string Descricao { get; set; }
        public int TempoIntervalo { get; set; }
        public Nullable<int> CodRegraJornada { get; set; }
    
        public virtual TB_RegraJornada TB_RegraJornada { get; set; }
    }
}
