//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JornadaMaxima
    {
        public int CodJornadaMaxima { get; set; }
        public Nullable<System.TimeSpan> DirecaoContinua { get; set; }
        public Nullable<System.TimeSpan> TempoParada { get; set; }
        public Nullable<System.TimeSpan> IntervaloRepouso { get; set; }
        public Nullable<System.TimeSpan> HorasSemanais { get; set; }
    }
}
