//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Jornada
    {
        public int CodJornada { get; set; }
        public int CodVeiculo { get; set; }
        public int CodMotorista { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataFechamento { get; set; }
        public Nullable<System.DateTime> UltimaComunicacao { get; set; }
        public Nullable<int> CodRegraJornada { get; set; }
    
        public virtual TB_Motorista TB_Motorista { get; set; }
        public virtual TB_RegraJornada TB_RegraJornada { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
