//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LogSistema
    {
        public int CodLog { get; set; }
        public int CodUsuario { get; set; }
        public System.DateTime DataHora { get; set; }
        public Nullable<int> CodRegistroAlterado { get; set; }
        public int CodPagina { get; set; }
        public string Acao { get; set; }
        public string RegistroModificado { get; set; }
    
        public virtual TB_Pagina TB_Pagina { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
