//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Manutencao
    {
        public int CodManutencao { get; set; }
        public int CodServico { get; set; }
        public int CodVeiculo { get; set; }
        public System.DateTime DataUltimaRevisao { get; set; }
        public int HodometroUltimaRevisao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Descricao { get; set; }
        public string TipoManutencao { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataProximaRevisao { get; set; }
        public Nullable<int> HodometroProximaRevisao { get; set; }
    
        public virtual TB_Veiculo TB_Veiculo { get; set; }
        public virtual TB_Servico TB_Servico { get; set; }
    }
}
