//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Motorista
    {
        public TB_Motorista()
        {
            this.TB_Jornada = new HashSet<TB_Jornada>();
            this.TB_Mensagens = new HashSet<TB_Mensagens>();
        }
    
        public int CodMotorista { get; set; }
        public string PossuiDispositivo { get; set; }
        public string Dispositivo { get; set; }
        public string TempoLimite { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string CNH { get; set; }
        public System.DateTime VencimentoCNH { get; set; }
        public string Telefone { get; set; }
        public string RG { get; set; }
        public string CategoriaCNH { get; set; }
        public string PisPasep { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string NomePai { get; set; }
        public string NomeMae { get; set; }
        public string Celular { get; set; }
        public string TelefoneRefPessoal { get; set; }
        public string TelefoneRefComercial { get; set; }
        public string TipoSanguineo { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public string CEP { get; set; }
        public int CodCidade { get; set; }
        public string Status { get; set; }
        public Nullable<int> CodCliente { get; set; }
    
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual ICollection<TB_Jornada> TB_Jornada { get; set; }
        public virtual ICollection<TB_Mensagens> TB_Mensagens { get; set; }
    }
}
