//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Mensagens
    {
        public int CodMensagem { get; set; }
        public string TipoMensagem { get; set; }
        public System.DateTime DataEnvio { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodVeiculo { get; set; }
        public Nullable<long> CodEvento { get; set; }
        public Nullable<int> QuantidadeEnviada { get; set; }
        public Nullable<int> CodManutencao { get; set; }
        public string TipoEventoMensagem { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public Nullable<int> CodMotorista { get; set; }
        public Nullable<System.DateTime> DataVenctoCNH { get; set; }
        public Nullable<int> HodometroManutencao { get; set; }
    
        public virtual TB_Motorista TB_Motorista { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
