//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ModeloVeiculo
    {
        public int CodModeloVeic { get; set; }
        public string Nome { get; set; }
        public string CodModeloFipe { get; set; }
        public int CodMarca { get; set; }
    
        public virtual TB_Marca TB_Marca { get; set; }
    }
}
