//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Marca
    {
        public TB_Marca()
        {
            this.TB_ModeloVeiculo = new HashSet<TB_ModeloVeiculo>();
        }
    
        public int CodMarca { get; set; }
        public string NomeMarca { get; set; }
    
        public virtual ICollection<TB_ModeloVeiculo> TB_ModeloVeiculo { get; set; }
    }
}
