//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NotificaoVeiculo
    {
        public TB_NotificaoVeiculo()
        {
            this.TB_EmailNotificacao = new HashSet<TB_EmailNotificacao>();
            this.TB_SmsNotificacao = new HashSet<TB_SmsNotificacao>();
        }
    
        public int CodNotificacaoVeiculo { get; set; }
        public int CodVeiculo { get; set; }
        public Nullable<bool> MensagemSistema { get; set; }
        public Nullable<bool> AlertaSMS { get; set; }
        public Nullable<bool> AlertaEmail { get; set; }
        public string Notificacao { get; set; }
    
        public virtual ICollection<TB_EmailNotificacao> TB_EmailNotificacao { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
        public virtual ICollection<TB_SmsNotificacao> TB_SmsNotificacao { get; set; }
    }
}
