//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OrdemServico
    {
        public int CodOrdemServico { get; set; }
        public string Operacao { get; set; }
        public int CodCliente { get; set; }
        public int CodVeiculo { get; set; }
        public int CodRevisaoFuncionamento { get; set; }
        public string VeiculoKM { get; set; }
        public bool RastreadorInstalado { get; set; }
        public bool BloqueadorInstalado { get; set; }
        public bool PanicoInstalado { get; set; }
        public string OutroInstalado { get; set; }
        public string Combustivel { get; set; }
        public string Pneus { get; set; }
        public string BateriaSemCarga { get; set; }
        public string BateriaMarchaLenta { get; set; }
        public string BateriaSobCarga { get; set; }
        public string SituacaoBateria { get; set; }
        public string Solicitacoes { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
        public System.DateTime DataOperacao { get; set; }
        public string CPFInstalador { get; set; }
        public string CPFProprietario { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual TB_RevisaoFuncionamento TB_RevisaoFuncionamento { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
