//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Ocorrencia
    {
        public int CodOcorrencia { get; set; }
        public int CodCliente { get; set; }
        public int CodVeiculo { get; set; }
        public string Motorista { get; set; }
        public string Placa2 { get; set; }
        public string Placa3 { get; set; }
        public string Placa4 { get; set; }
        public Nullable<int> CodCidadeOrigem { get; set; }
        public Nullable<int> CodCidadeDestino { get; set; }
        public Nullable<int> CodCidadeOcorrencia { get; set; }
        public string Carga { get; set; }
        public string Ocorrencia { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Horario { get; set; }
        public string Endereco { get; set; }
        public string Atendente { get; set; }
        public string DescricaoFato { get; set; }
        public string ProvidenciasTomadas { get; set; }
        public Nullable<int> CodTipoOcorrencia { get; set; }
    
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Cidade TB_Cidade1 { get; set; }
        public virtual TB_Cidade TB_Cidade2 { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual TB_TipoOcorrencia TB_TipoOcorrencia { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
