//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Permissao
    {
        public int CodPermissao { get; set; }
        public int CodPerfil { get; set; }
        public int CodPagina { get; set; }
        public string Permissao { get; set; }
    
        public virtual TB_Pagina TB_Pagina { get; set; }
        public virtual TB_Perfil TB_Perfil { get; set; }
    }
}
