//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pagina
    {
        public TB_Pagina()
        {
            this.TB_LogSistema = new HashSet<TB_LogSistema>();
            this.TB_Permissao = new HashSet<TB_Permissao>();
        }
    
        public int CodPagina { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<TB_LogSistema> TB_LogSistema { get; set; }
        public virtual ICollection<TB_Permissao> TB_Permissao { get; set; }
    }
}
