//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Perfil
    {
        public TB_Perfil()
        {
            this.TB_PerfilRestricao = new HashSet<TB_PerfilRestricao>();
            this.TB_Permissao = new HashSet<TB_Permissao>();
            this.TB_Usuario = new HashSet<TB_Usuario>();
        }
    
        public int CodPerfil { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Personalizado { get; set; }
        public Nullable<int> CodTipoPerfil { get; set; }
    
        public virtual TB_TipoPerfil TB_TipoPerfil { get; set; }
        public virtual ICollection<TB_PerfilRestricao> TB_PerfilRestricao { get; set; }
        public virtual ICollection<TB_Permissao> TB_Permissao { get; set; }
        public virtual ICollection<TB_Usuario> TB_Usuario { get; set; }
    }
}
