//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PontosRota
    {
        public int CodPontosRota { get; set; }
        public int CodPonto { get; set; }
        public int PosicaoPonto { get; set; }
        public int CodRota { get; set; }
        public Nullable<int> Tolerancia { get; set; }
        public Nullable<System.TimeSpan> ToleranciaTempo { get; set; }
    
        public virtual TB_Pontos TB_Pontos { get; set; }
        public virtual TB_Rota TB_Rota { get; set; }
    }
}
