//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RevisaoFuncionamento
    {
        public TB_RevisaoFuncionamento()
        {
            this.TB_OrdemServico = new HashSet<TB_OrdemServico>();
        }
    
        public int CodRevisaoFuncionamento { get; set; }
        public string PainelDeInstrumentos { get; set; }
        public string Buzina { get; set; }
        public string Esquicho { get; set; }
        public string LimpadorParabrisaDiant { get; set; }
        public string LimpadorParabrisaTras { get; set; }
        public string VentilacaoForcada { get; set; }
        public string ArCondicionado { get; set; }
        public string Radio { get; set; }
        public string AcendedorCigarros { get; set; }
        public string VidroEletrico { get; set; }
        public string VidroPortaDiantDir { get; set; }
        public string VidroPortaDiantEsq { get; set; }
        public string VidroPortaTrasDir { get; set; }
        public string VidroPortaTrasEsq { get; set; }
        public string VidroDianteiro { get; set; }
        public string VidroTraseiro { get; set; }
        public string RetrovisorEletrico { get; set; }
        public string RetrovisorEsquerdo { get; set; }
        public string RetrovidorDireito { get; set; }
        public string RetrovisorInterno { get; set; }
        public string TravaEletrica { get; set; }
        public string LuzTeto { get; set; }
        public string Cinzeiro { get; set; }
        public string Tapetes { get; set; }
        public string CintoSeguranca { get; set; }
        public string ForroPorta { get; set; }
        public string ForroTeto { get; set; }
        public string QuebraSol { get; set; }
        public string BancosDianteiros { get; set; }
        public string BancosTraseiros { get; set; }
        public string Tabelie { get; set; }
        public string Volante { get; set; }
        public string FarolLE { get; set; }
        public string FarolLD { get; set; }
        public string FarolAuxiliarLD { get; set; }
        public string FarolAuxiliarLE { get; set; }
        public string LanternaTraseiraLD { get; set; }
        public string LanternaTraseiraLE { get; set; }
        public string Seta { get; set; }
        public string Freio { get; set; }
        public string Re { get; set; }
        public string Alarme { get; set; }
        public string ExtintorIncendio { get; set; }
        public string Calotas { get; set; }
        public string Estepe { get; set; }
        public string Macaco { get; set; }
        public string Triangulo { get; set; }
        public string ParaChoqueDiant { get; set; }
        public string ParaChoqueTras { get; set; }
        public string Placas { get; set; }
    
        public virtual ICollection<TB_OrdemServico> TB_OrdemServico { get; set; }
    }
}
