//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Rota
    {
        public TB_Rota()
        {
            this.TB_PontosRota = new HashSet<TB_PontosRota>();
            this.TB_RotasVeiculos = new HashSet<TB_RotasVeiculos>();
        }
    
        public int CodRota { get; set; }
        public int ToleranciaRaio { get; set; }
        public Nullable<System.TimeSpan> ToleranciaTempo { get; set; }
        public string NomeRota { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public string Status { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual ICollection<TB_PontosRota> TB_PontosRota { get; set; }
        public virtual ICollection<TB_RotasVeiculos> TB_RotasVeiculos { get; set; }
    }
}
