//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RegraJornada
    {
        public TB_RegraJornada()
        {
            this.TB_IntervaloJornada = new HashSet<TB_IntervaloJornada>();
            this.TB_Jornada = new HashSet<TB_Jornada>();
        }
    
        public int CodRegraJornada { get; set; }
        public string Nome { get; set; }
        public Nullable<int> PeriodoMaximo { get; set; }
        public Nullable<bool> HoraFicta { get; set; }
        public Nullable<int> CodCliente { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual ICollection<TB_IntervaloJornada> TB_IntervaloJornada { get; set; }
        public virtual ICollection<TB_Jornada> TB_Jornada { get; set; }
    }
}
