//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SaidasEquipamento
    {
        public int CodSaidaEquipamento { get; set; }
        public int CodVeiculoEquipamento { get; set; }
        public string Saida { get; set; }
    
        public virtual TB_VeiculosEquipamentos TB_VeiculosEquipamentos { get; set; }
    }
}
