//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Servico
    {
        public TB_Servico()
        {
            this.TB_Manutencao = new HashSet<TB_Manutencao>();
        }
    
        public int CodServico { get; set; }
        public string Nome { get; set; }
        public int Hodometro { get; set; }
        public int Meses { get; set; }
        public string Ativo { get; set; }
    
        public virtual ICollection<TB_Manutencao> TB_Manutencao { get; set; }
    }
}
