//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TratamentoAlerta
    {
        public int CodTratamento { get; set; }
        public System.DateTime DataTratamento { get; set; }
        public string Descricao { get; set; }
        public int CodAlerta { get; set; }
        public int CodUsuario { get; set; }
        public Nullable<int> ChaveAlerta { get; set; }
    
        public virtual TB_AlertaEventos TB_AlertaEventos { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
