//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TipoVeiculo
    {
        public TB_TipoVeiculo()
        {
            this.TB_Veiculo = new HashSet<TB_Veiculo>();
        }
    
        public int CodTipoVeiculo { get; set; }
        public string NomeTipo { get; set; }
        public string NomeImagem { get; set; }
        public string ImagemInativo { get; set; }
    
        public virtual ICollection<TB_Veiculo> TB_Veiculo { get; set; }
    }
}
