//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TipoPerfil
    {
        public TB_TipoPerfil()
        {
            this.TB_Perfil = new HashSet<TB_Perfil>();
        }
    
        public int CodTipo { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<TB_Perfil> TB_Perfil { get; set; }
    }
}
