//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TipoOcorrencia
    {
        public TB_TipoOcorrencia()
        {
            this.TB_Ocorrencia = new HashSet<TB_Ocorrencia>();
        }
    
        public int CodTipoOcorrencia { get; set; }
        public string TipoOcorrencia { get; set; }
    
        public virtual ICollection<TB_Ocorrencia> TB_Ocorrencia { get; set; }
        public virtual TB_TipoOcorrencia TB_TipoOcorrencia1 { get; set; }
        public virtual TB_TipoOcorrencia TB_TipoOcorrencia2 { get; set; }
    }
}
