//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuario
    {
        public TB_Usuario()
        {
            this.TB_Acesso = new HashSet<TB_Acesso>();
            this.TB_LogSistema = new HashSet<TB_LogSistema>();
            this.TB_TratamentoAlerta = new HashSet<TB_TratamentoAlerta>();
            this.TBS_Requisicao = new HashSet<TBS_Requisicao>();
        }
    
        public int CodUsuario { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Ativo { get; set; }
        public string CEP { get; set; }
        public string Bairro { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public Nullable<int> CodCidade { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public int CodPerfil { get; set; }
        public string NomeUsuario { get; set; }
        public string SenhaTemporaria { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public int CodFusoHorario { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
        public Nullable<int> ValorAtualizacaoAutomatica { get; set; }
    
        public virtual ICollection<TB_Acesso> TB_Acesso { get; set; }
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual TB_FusoHorario TB_FusoHorario { get; set; }
        public virtual ICollection<TB_LogSistema> TB_LogSistema { get; set; }
        public virtual TB_Perfil TB_Perfil { get; set; }
        public virtual ICollection<TB_TratamentoAlerta> TB_TratamentoAlerta { get; set; }
        public virtual ICollection<TBS_Requisicao> TBS_Requisicao { get; set; }
    }
}
