//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VeiculosEquipamentos
    {
        public TB_VeiculosEquipamentos()
        {
            this.TB_EntradasEquipamento = new HashSet<TB_EntradasEquipamento>();
            this.TB_SaidasEquipamento = new HashSet<TB_SaidasEquipamento>();
        }
    
        public int CodVeiculosEquipamentos { get; set; }
        public int CodVeiculo { get; set; }
        public int CodEquipamento { get; set; }
        public Nullable<System.DateTime> DataInstalacao { get; set; }
        public string Teste { get; set; }
        public string Ativo { get; set; }
    
        public virtual ICollection<TB_EntradasEquipamento> TB_EntradasEquipamento { get; set; }
        public virtual TB_Equipamento TB_Equipamento { get; set; }
        public virtual ICollection<TB_SaidasEquipamento> TB_SaidasEquipamento { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
