//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Verificacao
    {
        public TB_Verificacao()
        {
            this.TB_EventoVerificacao = new HashSet<TB_EventoVerificacao>();
            this.TB_EventoVerificacao1 = new HashSet<TB_EventoVerificacao>();
            this.TB_EventoVerificacao2 = new HashSet<TB_EventoVerificacao>();
        }
    
        public int CodVerificacao { get; set; }
        public int CodTipoVerificacao { get; set; }
        public Nullable<int> ValorTempoVelocidade { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual ICollection<TB_EventoVerificacao> TB_EventoVerificacao { get; set; }
        public virtual ICollection<TB_EventoVerificacao> TB_EventoVerificacao1 { get; set; }
        public virtual ICollection<TB_EventoVerificacao> TB_EventoVerificacao2 { get; set; }
        public virtual TB_TipoVerificacao TB_TipoVerificacao { get; set; }
    }
}
