//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VeiculosClientes
    {
        public int CodHistorico { get; set; }
        public int CodCliente { get; set; }
        public int CodVeiculo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<int> CodGerenciadorRiscos { get; set; }
        public string TipoCliente { get; set; }
        public string TipoGerenciador { get; set; }
        public Nullable<System.DateTime> ValidadeGerenciador { get; set; }
        public string Status { get; set; }
        public Nullable<int> CodVeicAnterior { get; set; }
    
        public virtual TB_Cliente TB_Cliente { get; set; }
        public virtual TB_Veiculo TB_Veiculo { get; set; }
    }
}
