//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_StatusRequisicao
    {
        public TBS_StatusRequisicao()
        {
            this.TBS_Requisicao = new HashSet<TBS_Requisicao>();
        }
    
        public int CodStatusRequisicao { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<TBS_Requisicao> TBS_Requisicao { get; set; }
    }
}
