//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_ImeiSimCard
    {
        public int CodEquipamento { get; set; }
        public string Imei { get; set; }
        public string SimCard { get; set; }
        public System.DateTime DataEnvio { get; set; }
    
        public virtual TB_Equipamento TB_Equipamento { get; set; }
    }
}
