//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_Evento
    {
        public TBS_Evento()
        {
            this.TB_EnderecosEventos = new HashSet<TB_EnderecosEventos>();
        }
    
        public long Id { get; set; }
        public int Equipamento { get; set; }
        public System.DateTime DataEvento { get; set; }
        public System.DateTime DataComunicacao { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public short Direcao { get; set; }
        public short Velocidade { get; set; }
        public short SinalGPS { get; set; }
        public int TipoEvento { get; set; }
        public short Bateria { get; set; }
        public short Temperatura { get; set; }
        public int Hodometro { get; set; }
        public Nullable<int> StatusEntradas { get; set; }
        public Nullable<int> StatusSaida { get; set; }
        public Nullable<bool> StatusIgnicao { get; set; }
        public Nullable<bool> StatusBotaoPanico { get; set; }
        public Nullable<bool> StatusBotaoAntiFurto { get; set; }
        public Nullable<bool> StatusSecaoAntenaGPS { get; set; }
        public Nullable<bool> StatusEntradaAuxiliar { get; set; }
        public Nullable<bool> StatusEntradaAuxiliar2 { get; set; }
        public Nullable<bool> StatusEntradaAuxiliar4 { get; set; }
        public Nullable<bool> StatusFimVidaUtilBateriaBkp { get; set; }
        public Nullable<bool> StatusFalhaBateriaBkp { get; set; }
        public Nullable<bool> StatusBateriaBkpBaixa { get; set; }
        public Nullable<bool> StatusVoltagemBateria { get; set; }
        public Nullable<bool> StatusBloqueio { get; set; }
        public Nullable<bool> StatusSirene { get; set; }
        public Nullable<bool> StatusSaidaAuxiliar { get; set; }
        public Nullable<bool> StatusSaidaAuxiliar2 { get; set; }
        public Nullable<bool> StatusSaidaAuxiliar3 { get; set; }
        public Nullable<bool> StatusSaidaAuxiliar4 { get; set; }
    
        public virtual ICollection<TB_EnderecosEventos> TB_EnderecosEventos { get; set; }
        public virtual TB_Equipamento TB_Equipamento { get; set; }
        public virtual TBS_TipoEvento TBS_TipoEvento { get; set; }
    }
}
