//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcxTrackWCF.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_Requisicao
    {
        public TBS_Requisicao()
        {
            this.TBS_RequisicaoApn = new HashSet<TBS_RequisicaoApn>();
            this.TBS_RequisicaoHodometro = new HashSet<TBS_RequisicaoHodometro>();
            this.TBS_RequisicaoServer = new HashSet<TBS_RequisicaoServer>();
            this.TBS_RequisicaoSleepConfig = new HashSet<TBS_RequisicaoSleepConfig>();
            this.TBS_RequisicaoTempoTransmissao = new HashSet<TBS_RequisicaoTempoTransmissao>();
        }
    
        public int CodRequisicao { get; set; }
        public int CodEquipamento { get; set; }
        public Nullable<int> CodSaida { get; set; }
        public Nullable<int> CodAtivacao { get; set; }
        public Nullable<int> CodInvertida { get; set; }
        public int CodStatusRequisicao { get; set; }
        public Nullable<int> CodTipoRequisicao { get; set; }
        public Nullable<int> CodEntrada { get; set; }
        public Nullable<int> OpcoesEntrada { get; set; }
        public Nullable<int> TempoDeteccao { get; set; }
        public Nullable<int> NivelAtivacaoLogica { get; set; }
        public Nullable<int> AssociacaoDeSaidas { get; set; }
        public Nullable<System.DateTime> DataRequisicao { get; set; }
        public Nullable<int> CodUsuario { get; set; }
    
        public virtual TB_Equipamento TB_Equipamento { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
        public virtual TBS_StatusRequisicao TBS_StatusRequisicao { get; set; }
        public virtual TBS_TipoRequisicao TBS_TipoRequisicao { get; set; }
        public virtual ICollection<TBS_RequisicaoApn> TBS_RequisicaoApn { get; set; }
        public virtual ICollection<TBS_RequisicaoHodometro> TBS_RequisicaoHodometro { get; set; }
        public virtual ICollection<TBS_RequisicaoServer> TBS_RequisicaoServer { get; set; }
        public virtual ICollection<TBS_RequisicaoSleepConfig> TBS_RequisicaoSleepConfig { get; set; }
        public virtual ICollection<TBS_RequisicaoTempoTransmissao> TBS_RequisicaoTempoTransmissao { get; set; }
    }
}
